name: CI/CD Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install django pillow stripe
        fi
        pip install pytest pytest-django coverage bandit
    - name: Establecer variable de entorno para tests
      run: |
        echo "DEVELOPMENT=1" >> $GITHUB_ENV
        echo "DJANGO_SETTINGS_MODULE=tienda.settings" >> $GITHUB_ENV
    - name: Ejecutar pruebas con coverage
      run: |
        python -m coverage run --source='.' manage.py test || true
        python -m coverage xml -o coverage.xml
        python -m coverage report
    - name: Ejecutar análisis de seguridad básico
      run: |
        bandit -r . -x ./venv,./tests,./*/migrations -ll -f json -o bandit-results.json || true
    - name: Subir resultados de análisis
      uses: actions/upload-artifact@v4
      with:
        name: security-analysis
        path: |
          bandit-results.json
          coverage.xml

  deploy-dev:
    needs: build-and-test
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/feature/security_team7'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy a desarrollo
        run: |
          echo "Desplegando a entorno de desarrollo"
          echo "Rama actual: ${{ github.ref }}"
          # Aquí irían los comandos para desplegar a desarrollo

  deploy-prod:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy a producción
        run: |
          echo "Desplegando a entorno de producción"
          echo "Rama actual: ${{ github.ref }}"
          # Aquí irían los comandos para desplegar a producción 