name: SCA Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install django pillow stripe
          fi
          pip install pip-audit safety

      # Análisis con Safety
      - name: Run Safety
        run: |
          mkdir -p ./sca-reports
          pip freeze > requirements-freeze.txt
          safety check -r requirements-freeze.txt --json > ./sca-reports/safety-results.json || true
          echo "Análisis Safety completado"

      # Análisis con pip-audit
      - name: Run pip-audit
        run: |
          pip-audit --format json > ./sca-reports/pip-audit-results.json || true
          echo "Análisis pip-audit completado"

      # Generar un informe de texto para facilitar la lectura
      - name: Generate text report
        run: |
          echo "# Análisis de Dependencias" > ./sca-reports/sca-report.txt
          echo "## Safety Check" >> ./sca-reports/sca-report.txt
          echo "Ejecutado en: $(date)" >> ./sca-reports/sca-report.txt
          echo "\`\`\`" >> ./sca-reports/sca-report.txt
          safety check -r requirements-freeze.txt || true >> ./sca-reports/sca-report.txt
          echo "\`\`\`" >> ./sca-reports/sca-report.txt
          echo "## Pip Audit" >> ./sca-reports/sca-report.txt
          pip-audit || true >> ./sca-reports/sca-report.txt

      # Subir resultados
      - name: Upload SCA results
        uses: actions/upload-artifact@v4
        with:
          name: sca-reports
          path: ./sca-reports/ 